os: linux
dist: xenial
language: generic
services:
  - docker

before_install:
  - docker build -t sarangkartikey50/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sarangkartikey50/client-test yarn test -- --coverage

after_success:
  - docker build -t sarangkartikey50/multi-client ./client
  - docker build -t sarangkartikey50/multi-nginx ./nginx
  - docker build -t sarangkartikey50/multi-worker ./worker
  - docker build -t sarangkartikey50/multi-server ./server

  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin

  - docker push sarangkartikey50/multi-client
  - docker push sarangkartikey50/multi-nginx
  - docker push sarangkartikey50/multi-worker
  - docker push sarangkartikey50/multi-server